---
title: "Racial Heterogeneity Variable Construction"
author: "Bernard A. Coles IV"
date: "10/21/2018"
output: html_document
---
###Loading the Data
```{r message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(dplyr)
library(gridExtra)
library(rethinking)
library(kableExtra)
library(ggthemes)
library(knitr)

#Windows
#load("E:/Repository/Biso/Biso/data/wave1.rda")
#load("E:/Repository/Biso/Biso/data/network.wave1.rda")
#load("E:/Repository/Biso/Biso/data/weights.rda")

#Mac
load("~/desktop/Repository/Biso/data/wave1.rda")
load("~/desktop/Repository/Biso/data/network.wave1.rda")
load("~/desktop/Repository/Biso/data/weights.rda")

#Renamed
wave1.data <- da21600.0001
network.data <- da21600.0003
weights <- da21600.0004
```

###Consolidating the Data
```{r message=FALSE, warning=FALSE, include=FALSE}
#Merging Relevant Variables into one Data Frame
data1 <- wave1.data %>%
  dplyr :: select(AID, H1FV2, H1FV3, H1FV4, H1FV6, S6A, S6B, S6C, S6D, S6E, S4, S1, S2, PA55, H1FV9)

data2 <-  network.data %>%
  dplyr :: select(AID, ESRDEN, BCENT10X, IDGX2, SEG1RCE5, ERNRC5, EHRC5, AXS59A, AXS59B, AXS59C, AXS59D, AXS59E, AXS59F, AXS59G, SRCE51, SRCE52, SRCE53, SRCE54, SRCE55)

data3 <- weights %>%
  dplyr :: select(AID, GSWGT1)

mydata <- merge(data1, data2, by = "AID") 
#mydata <- merge(my.data, data3, by = "AID")
```

###Variable Cleaning and Construction 
```{r message=FALSE, warning=FALSE, include=FALSE}
#Race variable
mydata <- mydata %>%
  mutate(race = case_when(
    (S4 == "(1) (1) Yes (go to Q.5)" & S6A == "(1) (1) Marked") ~ "white latino",
    (S4 == "(1) (1) Yes (go to Q.5)" & S6B == "(1) (1) Marked") ~ "black latino",
    (S6A == "(1) (1) Marked" & S6B== "(1) (1) Marked") ~ "mixed race",
    (S6A == "(1) (1) Marked" & S6C == "(1) (1) Marked") ~ "mixed race",
    (S6A == "(1) (1) Marked" & S6D == "(1) (1) Marked") ~ "mixed race",
    (S6A == "(1) (1) Marked" & S6E == "(1) (1) Marked") ~ "mixed race",
    (S6B == "(1) (1) Marked" & S6C == "(1) (1) Marked") ~ "mixed race",
    (S6B == "(1) (1) Marked" & S6D == "(1) (1) Marked") ~ "mixed race",
    (S6B == "(1) (1) Marked" & S6E == "(1) (1) Marked") ~ "mixed race",
    (S6C == "(1) (1) Marked" & S6D == "(1) (1) Marked") ~ "mixed race",
    (S6C == "(1) (1) Marked" & S6E == "(1) (1) Marked") ~ "mixed race",
    (S6D == "(1) (1) Marked" & S6E == "(1) (1) Marked") ~ "mixed race",
    S4 == "(1) (1) Yes (go to Q.5)" ~ "latino", 
    S6A == "(1) (1) Marked" ~ "white",
    S6B == "(1) (1) Marked" ~ "black", 
    S6C == "(1) (1) Marked" ~ "asian", 
    S6D == "(1) (1) Marked" ~ "native american", 
    S6E == "(1) (1) Marked" ~ "other",
    T ~ NA_character_))

#Victimization
mydata <- mydata %>%
  mutate(victim = case_when(
    (H1FV2 == "(1) (1) Once" |  H1FV2 == "(2) (2) More than once") ~ 1,
    (H1FV3 == "(1) (1) Once" |  H1FV3 == "(2) (2) More than once") ~ 1,
    (H1FV4 == "(1) (1) Once" |  H1FV4 == "(2) (2) More than once") ~ 1,
    (H1FV6 == "(1) (1) Once" |  H1FV6 == "(2) (2) More than once") ~ 1,
    H1FV2 == "(0) (0) Never" ~ 0,
    H1FV3 == "(0) (0) Never" ~ 0,
    H1FV4 == "(0) (0) Never" ~ 0,
    H1FV6 == "(0) (0) Never" ~ 0,
    T ~ NA_real_))
#Dependent Variable Breakdown Table 
mydata <- mydata %>%
  mutate(knife.gun = case_when(
    (H1FV2 == "(1) (1) Once" |  H1FV2 == "(2) (2) More than once") ~ 1,
    H1FV2 == "(0) (0) Never" ~ 0,
    T ~ NA_real_))
mydata <- mydata %>%
  mutate(shot = case_when(
    (H1FV3 == "(1) (1) Once" |  H1FV3 == "(2) (2) More than once") ~ 1,
    H1FV3 == "(0) (0) Never" ~ 0,
    T ~ NA_real_))
mydata <- mydata %>%
  mutate(stabbed = case_when(
    (H1FV4 == "(1) (1) Once" |  H1FV4 == "(2) (2) More than once") ~ 1,
    H1FV4 == "(0) (0) Never" ~ 0,
    T ~ NA_real_))
mydata <- mydata %>%
  mutate(jumped = case_when(
    (H1FV6 == "(1) (1) Once" |  H1FV6 == "(2) (2) More than once") ~ 1,
    H1FV6 == "(0) (0) Never" ~ 0,
    T ~ NA_real_))

#Creating the Network Delinquency Variable
mydata <- mydata %>%
  mutate(network.delinquency = (AXS59A + AXS59B + AXS59C + AXS59D + AXS59E + AXS59F + AXS59G)/7) 

#Cleaning Control Variables 
mydata <- mydata %>%
  mutate(female = case_when(
    S2 == "(1) (1) Male" ~ 0,
    S2 == "(2) (2) Female" ~ 1,
    T ~ NA_real_))

mydata$age <- mydata$S1
mydata$family.income <- mydata$PA55

mydata <- mydata %>%
  mutate(weapon.carry = case_when(
    H1FV9 == "(0) (0) None (skip to Q.11)" ~ 0, 
    (H1FV9 == "(1) (1) 1 day" | H1FV9 == "(2) (2) 2 or 3 days" | H1FV9 == "(3) (3) 4 or 5 days" | H1FV9 == "(4) (4) 6 or more days") ~ 1,
    T ~ NA_real_))

#Renaming Network Variables
mydata$racial.heterogeneity <- mydata$ERNRC5
mydata$dense <- mydata$ESRDEN
mydata$centrality <- mydata$BCENT10X
mydata$popularity <- mydata$IDGX2

mydata <- mydata %>%
  mutate(density = case_when(
    (popularity == 0 & centrality == 0) ~ 0,
    T ~ dense))

#Variable Selection 
mydata.dv <- mydata %>%
  select(knife.gun, shot, stabbed, jumped)

mydata <- mydata %>%
  select(AID, victim, race, female, age, family.income, weapon.carry, racial.heterogeneity, network.delinquency, popularity, centrality, density)

#Only complete rows Kept
mydata.c <- mydata[complete.cases(mydata), ]
```

###Model Construction
```{r message=FALSE, warning=FALSE, include=FALSE}
model <- map(alist(
  victim ~ dbinom(1, p),
  logit(p) <- a + b1*age + b2*female + b3*family.income + b4*weapon.carry + b5*racial.heterogeneity + b6*network.delinquency + b7*popularity + b8*centrality + b9*density,
  a ~ dnorm(0,10),
  b1 ~ dnorm(0,10),
  b2 ~ dnorm(0,10),
  b3 ~ dnorm(0,10),
  b4 ~ dnorm(0,10),
  b5 ~ dnorm(0,10),
  b6 ~ dnorm(0,10), 
  b7 ~ dnorm(0,10), 
  b8 ~ dnorm(0,10), 
  b9 ~ dnorm(0,10)), data=mydata.c, start=list(b1=0, b2=0, b3=0, b4=0, b5=0, b6=0, b7=0, b8=0, b9=0))

imodel1 <- map(alist(
  victim ~ dbinom(1, p),
  logit(p) <- a + b1*age + b2*female + b3*family.income + b4*weapon.carry + b5*racial.heterogeneity + b6*network.delinquency + b7*popularity + b8*centrality + b9*density + b10*racial.heterogeneity*centrality,
  a ~ dnorm(0,10),
  b1 ~ dnorm(0,10),
  b2 ~ dnorm(0,10),
  b3 ~ dnorm(0,10),
  b4 ~ dnorm(0,10),
  b5 ~ dnorm(0,10),
  b6 ~ dnorm(0,10), 
  b7 ~ dnorm(0,10), 
  b8 ~ dnorm(0,10), 
  b9 ~ dnorm(0,10)), data=mydata.c, start=list(b1=0, b2=0, b3=0, b4=0, b5=0, b6=0, b7=0, b8=0, b9=0, b10=0))

imodel2 <- map(alist(
  victim ~ dbinom(1, p),
  logit(p) <- a + b1*age + b2*female + b3*family.income + b4*weapon.carry + b5*racial.heterogeneity + b6*network.delinquency + b7*popularity + b8*centrality + b9*density + b10*racial.heterogeneity*popularity,
  a ~ dnorm(0,10),
  b1 ~ dnorm(0,10),
  b2 ~ dnorm(0,10),
  b3 ~ dnorm(0,10),
  b4 ~ dnorm(0,10),
  b5 ~ dnorm(0,10),
  b6 ~ dnorm(0,10), 
  b7 ~ dnorm(0,10), 
  b8 ~ dnorm(0,10), 
  b9 ~ dnorm(0,10)), data=mydata.c, start=list(b1=0, b2=0, b3=0, b4=0, b5=0, b6=0, b7=0, b8=0, b9=0, b10=0))

imodel3 <- map(alist(
  victim ~ dbinom(1, p),
  logit(p) <- a + b1*age + b2*female + b3*family.income + b4*weapon.carry + b5*racial.heterogeneity + b6*network.delinquency + b7*popularity + b8*centrality + b9*density + b10*racial.heterogeneity*density,
  a ~ dnorm(0,10),
  b1 ~ dnorm(0,10),
  b2 ~ dnorm(0,10),
  b3 ~ dnorm(0,10),
  b4 ~ dnorm(0,10),
  b5 ~ dnorm(0,10),
  b6 ~ dnorm(0,10), 
  b7 ~ dnorm(0,10), 
  b8 ~ dnorm(0,10), 
  b9 ~ dnorm(0,10)), data=mydata.c, start=list(b1=0, b2=0, b3=0, b4=0, b5=0, b6=0, b7=0, b8=0, b9=0, b10=0))

m <- as.data.frame((model@coef),1)
m1 <- as.data.frame((imodel1@coef),1)
m2 <- as.data.frame((imodel2@coef),1)
m3 <- as.data.frame((imodel3@coef),1)

t4 <- m %>%
  mutate(OR = exp((model@coef))) %>%
  select(OR)

x <- m1 %>%
  mutate(OR = exp((imodel1@coef))) %>%
  select(OR)

y <- m2 %>%
  mutate(OR = exp((imodel2@coef))) %>%
  select(OR)

z <- m3 %>%
  mutate(OR = exp((imodel3@coef)))%>%
  select(OR)

inames <- c("Age", "Sex", "Family Income", "Weapon Carry", "Network Delinquency", "Popularity", "Centrality", "Density", "Interaction Term", "Intercept")

names <- c("Age", "Sex", "Family Income", "Weapon Carry", "Network Delinquency", "Popularity", "Centrality", "Density", "Intercept")

t4 <- round(t4, digits = 3)
x <- round(x, digits = 3)
y <- round(y, digits = 3)
z <- round(z, digits = 3)


rownames(t4) <- names
rownames(m1) <- inames 
rownames(m2) <- inames 
rownames(m3) <- inames 


t5 <- cbind(x, y, z)

table4 <- kable(t4, caption = "Logistic Regression Model", "latex", booktabs = T) %>%
  add_header_above(c("Predictors", "Model 1" = 1)) %>%
  kable_styling("striped")

table5 <- kable(t5, caption = "Interaction Models", "latex", booktabs = T) %>%
  add_header_above(c("Predictors", "Model 2" = 1, "Model 3" = 1, "Model 4" = 1)) %>%
  kable_styling("striped")
```

###Descriptive Statistics & Tables
```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
race.plot <- mydata.c %>%
  filter(race != is.na(race)) %>%
  ggplot(aes(x = race, fill = race)) +
  geom_bar() + guides(fill = F) + 
  coord_flip() +
  labs(title = "Racial Composition of Respondents", y = "Counts", x = " ") +
  scale_colour_pander() +
  scale_fill_pander() +
  theme_pander() + 
  theme(text = element_text(family = "Times"), plot.title = element_text(hjust = 0.5), legend.position = "none") 


race.victim <- mydata.c %>%
  ggplot(aes(x = race)) +
  geom_bar(aes(fill = as.character(victim)), position = "fill") + guides(fill = F) + 
  geom_hline(yintercept=(mean(mydata.c$victim)), linetype = "dashed", color = "red3") +
  coord_flip() +
  labs(title = "Victimization by Race", y = "Proportion of Victims", x = " ") +
  scale_colour_pander() +
  scale_fill_pander() +
  theme_pander() + 
  theme(text = element_text(family = "Times"), plot.title = element_text(hjust = 0.5), legend.position = "none") 


#Native American and Black Latinos are the most victimized racial groups
a <- mydata %>%
  filter(race != is.na(race)) %>%
  group_by(race) %>%
  summarise(victim = mean(victim, na.rm = T)) 

#victim rate close to mean for non carriers, much higher for carriers ~ 0.58
b <- mydata %>%
  group_by(weapon.carry) %>%
  summarise(victim = mean(victim, na.rm = T))

#Dependent Variable Breakdown Summary
Proportion <- sapply(mydata.dv, mean, na.rm = T)
cont1 <- length(which(mydata.dv$knife.gun == 1))
cont2 <- length(which(mydata.dv$shot == 1))
cont3 <- length(which(mydata.dv$stabbed == 1))
cont4 <- length(which(mydata.dv$jumped == 1))
conts <- c(cont1, cont2, cont3, cont4)

names <- c("knife.gun", "shot", "stabbed", "jumped")
Counts <- rbind(conts, names)
colnames(Counts) <- names
Counts <- Counts[-2,1:4]
Proportion <- round(Proportion, digits = 3)
t1 <- cbind(Proportion, Counts)

table1 <- kable(t1, "latex", caption = "Dependent Variable Index", booktabs = T) %>%
  kable_styling(latex_options = "striped") %>%
  footnote(general = "N = 3145")


#Creating the Summary Statistics 
mydata.num <- mydata %>%
  select(-AID, -race)

Mean <- sapply(mydata.num, mean, na.rm= T)
Stdv <- sapply(mydata.num, sd, na.rm = T)
Min <- sapply(mydata.num, min, na.rm = T)
Median <- sapply(mydata.num, median, na.rm = T)
Max <- sapply(mydata.num, max, na.rm = T)

t2 <- data.frame(
  Items = c("Question 1","Question 2","Question 3","Question 4","Question 5","Question 6","Question 7"),
  Features = c("During the past twelve months, how often did you smoke cigarettes?", "During the past twelve months, how often did you drink beer, wine, liqour?", "During the past twelve months, how often did you get drunk?", "During the past twelve months, how often did you race on a bike, skateboard, roller blades, or in a boat or car?", "During the past twelve months, how often did you do something dangerous because you were dared to?", "During the past twelve months, how often did you lie to your parents or guardians?", "During the past twelve months, how often did you skip school without an excuse?"))

table2 <- kable(t2, caption = "Friendship Network Delinquency Index" , "latex", booktabs = T) %>% 
  kable_styling(full_width = F) %>% 
  column_spec(1, bold = T) %>% 
  column_spec(2, width = "30em")

t3 <- round(cbind(Mean, Stdv, Min, Median, Max), digits=3)

table3 <- kable(t3, caption = "Descriptive Statistics","latex", booktabs = T) %>%
  kable_styling(latex_options = "striped") %>%
  footnote(general = "N = 3145")
```

###Comparing the Models with Information Criteria
```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
compare(model, imodel1, imodel3)
compare(model, imodel2, imodel3)
compare(model, imodel1, imodel2, imodel3)

#Code to return a clean table with the best model on top -> must translate for map models 
#model_weights(b6.11, b6.12, b6.13, b6.14, 
              #weights = "waic") %>%
  #as_tibble() %>% 
  #rename(weight = value) %>% 
  #mutate(model  = c("b6.11", "b6.12", "b6.13", "b6.14"),
         #weight = weight %>% round(digits = 2)) %>% 
  #select(model, weight) %>% 
  #arrange(desc(weight)) %>% 
  #knitr::kable()
```

###Visualizing Centrality Model
```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
#New data frame with variables held constant - Interaction terms held at quantiles
age <- mean(mydata.c$age)
female <- mean(mydata.c$female)
family.income <- mean(mydata.c$family.income)
weapon.carry <- mean(mydata.c$weapon.carry)
racial.heterogeneity <- seq(0, 1, by = .05)
network.delinquency <- mean(mydata.c$network.delinquency)
popularity <- mean(mydata.c$popularity)
centrality <- quantile(mydata.c$centrality, c(.1, .5, .9))
density <- mean(mydata.c$density)


predictions <- as.tibble(expand.grid(age, female, family.income, weapon.carry, racial.heterogeneity, network.delinquency, popularity, centrality, density))   
colnames(predictions) <- c("age", "female", "family.income", "weapon.carry", "racial.heterogeneity", "network.delinquency", "popularity", "centrality", "density")      


#inv_logit_scaled() logistic() for BRMS models that you should probably try to run. 

#Predicted Likelihood of Victimization added to the newdata 
samples <- predictions %>%             
  mutate(victim = logistic(m1[10,] + m1[1,]*age + m1[2,]*female + m1[3,]*family.income + m1[4,]*weapon.carry + m1[5,]*racial.heterogeneity + m1[6,]*network.delinquency + m1[7,]*popularity + m1[8,]*centrality + m1[8,]*density + m1[10,]*racial.heterogeneity*centrality)) %>%         
  group_by(racial.heterogeneity, centrality) %>%                              
  slice(1)

#Visualize: Centrality Interactions
samples$centrality <- as.character(samples$centrality)
samples <- samples %>%
  mutate(Centrality = case_when(
    centrality == "0" ~ "10th Percentile",
    centrality == "0.78677539864745" ~ "50th Percentile",
    centrality == "1.70187217534238"  ~ "90th Percentile",
    T ~ NA_character_))

plot1 <- ggplot(samples, aes(x = racial.heterogeneity , group = Centrality)) +
  geom_line(aes(y = victim, color = Centrality), size = 1.5) +
  labs(title = "The Conditional Effects of Network Structure and Form on Victimization", subtitle = "The Interaction Effects of Centrality & Racial Heterogeneity", x = "Ego Network Racial Heterogeneity", y = "Probability of Victimization") +
  scale_colour_pander() +
  scale_fill_pander() +
  theme_pander() + 
  theme(text = element_text(family = "Times"), plot.title = element_text(hjust = 0.5), plot.subtitle = element_text(hjust = 0.5))
```

###Visualizing Popularity Model 
```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
#New data frame with variables held constant - Interaction terms held at quantiles
age <- mean(mydata.c$age)
female <- mean(mydata.c$female)
family.income <- mean(mydata.c$family.income)
weapon.carry <- mean(mydata.c$weapon.carry)
racial.heterogeneity <- seq(0,1, by = .01)
network.delinquency <- mean(mydata.c$network.delinquency)
centrality <- mean(mydata.c$centrality)
popularity <- quantile(mydata.c$popularity, c(.1, .5, .9))
density <- mean(mydata.c$density)


predictions <- as.tibble(expand.grid(age, female, family.income, weapon.carry, racial.heterogeneity, network.delinquency, popularity, centrality, density))   
colnames(predictions) <- c("age", "female", "family.income", "weapon.carry", "racial.heterogeneity", "network.delinquency", "popularity", "centrality", "density")  


#Predicted Likelihood of Victimization added to the newdata 
samples <- predictions %>%             
  mutate(victim = logistic(m2[10,] + m2[1,]*age + m2[2,]*female + m2[3,]*family.income + m2[4,]*weapon.carry + m2[5,]*racial.heterogeneity + m2[6,]*network.delinquency + m2[7,]*popularity + m2[8,]*centrality + m2[8,]*density + m2[10,]*racial.heterogeneity*populairty)) %>%         
  group_by(racial.heterogeneity, popularity) %>%                              
  slice(1)

#Visualize: Centrality Interactions
samples <- samples %>%
  mutate(Popularity = case_when(
    popularity == 1 ~ "10th Percentile",
    popularity == 4 ~ "50th Percentile",
    popularity == 10  ~ "90th Percentile",
    T ~ NA_character_))

samples$Popularity <- as.factor(samples$Popularity)

plot2 <- ggplot(samples, aes(x = racial.heterogeneity , group = Popularity)) +
  geom_line(aes(y = victim, color = Popularity) , size = 1.5) +
  labs(title = "The Conditional Effects of Network Structure and Form on Victimization", subtitle = "The Interaction Effects of Popularity & Racial Heterogeneity", x = "Ego Network Racial Heterogeneity", y = "Probability of Victimization") +
  scale_colour_pander() +
  scale_fill_pander() +
  theme_pander() + 
  theme(text = element_text(family = "Times"), plot.title = element_text(hjust = 0.5), plot.subtitle = element_text(hjust = 0.5))
```

###Visualizing Density Model
```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
#New data frame with variables held constant - Interaction terms held at quantiles
age <- mean(mydata.c$age)
female <- mean(mydata.c$female)
family.income <- mean(mydata.c$family.income)
weapon.carry <- mean(mydata.c$weapon.carry)
racial.heterogeneity <- seq(0,1, by = .01)
network.delinquency <- mean(mydata.c$network.delinquency)
centrality <- mean(mydata.c$centrality)
density <- quantile(mydata.c$density, c(.1, .5, .9))
popularity <- mean(mydata.c$popularity)


predictions <- as.tibble(expand.grid(age, female, family.income, weapon.carry, racial.heterogeneity, network.delinquency, popularity, centrality, density))   
colnames(predictions) <- c("age", "female", "family.income", "weapon.carry", "racial.heterogeneity", "network.delinquency", "popularity", "centrality", "density")  


#Predicted Likelihood of Victimization added to the newdata 
samples <- predictions %>%             
  mutate(victim = logistic(m3[10,] + m3[1,]*age + m3[2,]*female + m3[3,]*family.income + m3[4,]*weapon.carry + m3[5,]*racial.heterogeneity + m3[6,]*network.delinquency + m3[7,]*popularity + m3[8,]*centrality + m3[8,]*density + m3[10,]*racial.heterogeneity*density)) %>%         
  group_by(racial.heterogeneity, density) %>%                              
  slice(1)


#Visualize: Centrality Interactions
samples$density <- as.character(samples$density)

samples <- samples %>%
  mutate(Density = case_when(
    density == "0.1571428571429" ~ "10th Percentile",
    density == "0.2619047619048" ~ "50th Percentile",
    density == "0.5"  ~ "90th Percentile",
    T ~ NA_character_))

plot3 <- ggplot(samples, aes(x = racial.heterogeneity , group = Density)) +
  geom_line(aes(y = victim, color = Density) , size = 1.5) +
  labs(title = "The Conditional Effects of Network Structure and Form on Victimization", subtitle = "The Interaction Effects of Density & Network Delinquency", x = "Ego Network Racial Heterogeneity", y = "Probability of Victimization") +
  scale_colour_pander() +
  scale_fill_pander() +
  theme_pander() + 
  theme(text = element_text(family = "Times"), plot.title = element_text(hjust = 0.5),  plot.subtitle = element_text(hjust = 0.5))
```

###Racial Heterogeneity Figures
```{r}
racial.heterogeneity <- quantile(mydata.c$racial.heterogeneity, c(.33, .66))
  
mydata.c <- mydata.c %>%
  mutate(rh.cat = case_when(
    racial.heterogeneity <= .33 ~ "Low", #Bottom 1/3
    (racial.heterogeneity > .33 & racial.heterogeneity <= .66) ~ "Middle", #Between 1/3 and 2/3
    racial.heterogeneity > .66 ~ "High", #Top 1/3
    T ~ NA_character_))

racial.heterogeneity.levels <- c("Low", "Middle", "High")

mydata.c <- mydata.c %>%
  mutate(rh.cat = factor(rh.cat, levels = racial.heterogeneity.levels, ordered = T))
  
(rh.victim <- mydata.c %>%
  ggplot(aes(x = rh.cat)) +
  geom_bar(aes(fill = as.character(victim)), position = "fill") +
  geom_hline(yintercept= mean(mydata.c$victim), linetype = "dashed") +
  ylim(0, .22) + 
  annotate("text", x = 1, y = 0.2, label = "Mean\nVictimization", size = 3) +
  coord_flip() +
  labs(title = "Racial Heterogeneity & Victimization", y = "Proportion of Victims", x = " ") +
  scale_fill_manual(values=c("white", "seagreen"), 
                       name="Victimization",
                       breaks=c("1", "0"),
                       labels=c("Victims", "Non-Victims")) + 
  theme_pander() + 
  theme(text = element_text(family = "Times"), plot.title = element_text(hjust = 0.5)))
  

ggsave("rh.victim.pdf", rh.victim, width = 25, height = 15, units = "cm")


network.delinquency <- quantile(mydata.c$network.delinquency, c(.5))

mydata.c <- mydata.c %>%
  mutate(Delinquency = case_when(
    network.delinquency <= .7143 ~ "Non Delinquents", #At or Below the 25th Percentile
    (network.delinquency > .7143 & network.delinquency < 1.4286) ~ "Average Teen", #IQR 
    network.delinquency >= 1.4286 ~ "Delinquents", #At or Above the 75th Percentile
    T ~ NA_character_))

(rh.delinquency <- mydata.c %>%
  ggplot(aes(x = rh.cat)) +
  geom_bar(aes(fill = Delinquency), position = "fill") + 
  coord_flip() +
  labs(title = "Racial Heterogeneity & Delinquency", y = "Proportion of Delinquents", x = " ") +
  scale_fill_pander() + 
  theme(text = element_text(family = "Times"), plot.title = element_text(hjust = 0.5)))

ggsave("rh.delinquency.pdf", rh.delinquency, width = 25, height = 15, units = "cm")

a <- grid.arrange(rh.victim, rh.delinquency, nrow = 2)

ggsave("rh.pdf", a, width = 25, height = 15, units = "cm")

```

























