---
title: "Final Project"
author: "Bernard A. Coles IV"
date: "3/5/2019"
output: pdf_document
---
(1) Research Question
(2) Not Necessary to deep dive into theory
###Introduction #1paragraph only
The formative years in the lives of many American teenagers take place within the context of public or private school systems. In these contexts, teens are consistently exposed to many opportunities to practice forming and maintaining social relationships. One potential outcome of adolescent social relations is the risk of engaging with delinquency and violence, especially when teens are unsupervised (Haynie & Osgood 2005). Adolescents remain at increased risk for victimization when compared to other age groups. In 1997, 202, 000 students were victims of nonfatal serious violent crimes at school, including rape, sexual assault, robbery, and aggravated assault. When adding simple assault to the above, a total of 1.1 million students were classified as being victimized in school (Van Dorn 2004). In fact, in the United States youth are more than 2.3 times more likely than the general population to be victims (Hanish and Guerra 2000). Important for this study are instances of serious nonfatal forms of victimization and their relationship to the content or behavioral norms of the network and the structural characteristics of the respondent’s position within the network. 
School-based risk factors for victimization have been studied extensively since data was collected for the 1977 Safe School Study conducted by the National Institute of Education (Van Dorn 2004). Some often-identified correlates of victimization are age and gender, which repeatedly show that younger adolescents and males are at the greatest risk of physical victimization (Warr, 1993). The prevalence, severity, and impacts of this problem have prompted increasing attention in recent years by national and international researchers who are committed to providing youth with safer schools (Hanish and Guerra 2000). However, Van Dorn (2004) found that school-based safety precautions did not significantly reduce violent victimization and only showed a trend toward significance with nonviolent victimization, suggesting that our high schools have much to improve regarding policies geared towards preventing teens from engaging in violence on campus. 
Sociological research on adolescent crime and delinquency suggests that the social characteristics of an adolescent’s community heavily influence the likelihood of that adolescent’s involvement in delinquent behavior and perhaps the likelihood of their victimization (Hanish and Guerra 2000; Schreck, Fisher, and Miller 2004; Mouttapa, Valente, Gallaher, Rohrbach and Unger 2004; Sampson 1984; Moody 2001; Berg, Brunson, and Stewart 2012; Sampson and Groves 1989; Pridemore 2002; Evans and Smokoski 2016; Shaw and Mckay ([1942] 1969); Hirschi 1969; Sutherland and Cressey 1974). Schreck et al. (2004) speculate that research on victimization could benefit from studies emphasizing the peer influences generated by delinquent groups, because delinquency and victimization share many empirical connections. Their study identified peer delinquency as a significant risk factor for violent victimization. Additionally, Hirschi’s (1969) theory of social control and Sutherland’s (1974) theory of differential association have both empirically verified a connection between social networks and delinquency/crime and have been adapted and replicated by modern sociologists such as Haynie (2001), Matsueda (1982), and Mangino (2009). For example, Haynie (2001) shows that any structural network location that puts one in a position of greater influence within the group amplifies an individual’s delinquency above the delinquent content of the peer network. Just as there is a relationship between network position and delinquency, it follows, that there is a likely connection between the social network occupied by an adolescent and his/her chances of becoming a victim. However, the likelihood of victimization compared to the propensity towards delinquency may function differently in terms of causal mechanisms, particularly the mediating effects of the network’s structure. I posit that network structure influences how an individual may learn appropriate behavior and that the specific behaviors they adopt will either enhance or limit their exposure to violence. 

###Data
*Add Health*
To test a friendship network’s influence on violent victimization, this study employs the public use  data from the first wave of the National Longitudinal Study of Adolescent to Adult Health (Add Health ). The data consists of a nationally representative sample of teens, grades 7 – 12, nested in randomly selected public and private schools throughout the United States in 1994-95. Information on the sample was collected from the respondents, their peers, school administrators, parents, siblings, and romantic partners through an initial in-school survey followed by four in-home interviews. 

*In-School Surveys*
Add Health’s In-School Questionnaire, a self-administered instrument, was distributed to more than 90,000 students in grades 7 through 12 in an hour-long class period between fall 1994 and spring 1995. The questionnaire consisted of many topics, from education and parental occupation to self-esteem and risk behaviors, but most important to this study was the information collected on student’s behaviors and friendships. Respondents were asked to name their five closest female friends and their five closest male friends. In instances where the friendship nominations were members of the same school as the respondent, as more than 80 percent of nominations were, they too were respondents, meaning that data was also available on them. Because Add Health project staff assigned an identification number to each student and recorded these nominations by each student’s registered ID it is possible to reconstruct the social networks for most students. This network information makes it possible to calculate behavioral attributes present in each respondent’s own friendship (ego) network, such as delinquency, as well as test the structural influences the network may have on behavior or propensity to victimization. 

*In-Home Interviews*
Data from the more in-depth in-home interviews contains sensitive information on the adolescents such as experience with drugs and alcohol and various other risky behaviors such as carrying a weapon. One of the most advantageous components of this in-home method was the use of laptop computers which played prerecorded questions about experiences with victimization. This method of data collection helped to maintain confidentiality on numerous sensitive subjects. These self-reported experiences from the first wave of in-home interviews was used to construct the dependent variable – victim violence – for this study. Therefore, the research sample for this project comes from the in-home wave 1 respondents with the network data from the in-school survey data as an addition to the sample. The final research sample for the study consisted of 4172 observations.

###Variable Construction
*The Dependent Variable: Violent Victimization*
The variable victim violence is a composite indicator of victimization experienced in the twelve months prior to the wave 1 in-home interviews. It takes on the value of 0, if the respondent experienced none of the forms of physical victimization listed in Table 2, or 1 if they have experienced at least one of the forms. The variable was designed to measure purely physical manifestations of victimization i.e. being shot, stabbed or jumped. Table 1 shows that the victimization variable has a mean of .19 and a standard deviation of .39 for the research sample.

*Popularity, Centrality, and Standing out*
Being a highly visible member, that is standing out, in a delinquent network is likely to increase one’s chances of becoming a victim, as theorized above. Two variables have been chosen to operationalize this concept. Popularity is a measure of the number of friendship nominations received by the respondent. The nominations range from 0 to 30 with a mean of 4.81 and a standard deviation of 3.79. When a person receives more friendship nominations it is a stark example of high visibility with in an adolescent’s school. 
The second operationalization of standing out is centrality. Centrality is a measure of the number of links required to link all other peers in the adolescent’s friendship network. Centrally situated adolescents stand out because they are a focal node, much of the information flowing through the network flows through members with high centrality scores. The centrality variable is calculated in the Add Health data using Bonacich’s formula (Bonacich 1987). Centrality for the research sample has a mean of .85 and a standard deviation of .62. The variable ranges from 0 to 4.29. 

*Density and Blending In*
The concept of blending in is operationalized by the variable density. A highly dense network is marked by uniformity and a lack of individuality (Bearman, 1991). When there is less individuality, each member stands out less, that is, they blend in more. High density thus functions to provide the protective shell discussed above when coupled with higher rates of peer delinquency. The variable is defined as the number of ties in the adolescent’s friendship network divided by the total number of ties possible. The variable is represented in the research sample as a percentage and ranges from 7.6 to 100. The mean for the sample is 29.72 with a standard deviation of 14.01. 

*Weapon Carrying* 

*Network Delinquency*
###Methods/Analytic Strategy: Rigorously graded, why you chose models, why these priors. 
The dependent variable for this paper is dichotomous and therefore, the normal assumptions of ordinary least squared regression cannot be maintained. To compensate, logistic regression analysis, designed to handle dependent variables of this nature, was used to analyze the data. The logistic regression analysis for this project interprets the odds ratios for the independent variables that represent the individual variable’s influence on the likelihood of victimization while holding all other variables in the equation constant. An odds ratio of 1.5 can be understood as a 50% increase in the likelihood of violent victimization for the given variable net of the other variables present in the equation. On the other hand, an odds ratio of .5 signifies a 50% decrease in the likelihood of violent victimization for the variable in question while controlling for all other variables present in the model.
The statistical method used in this paper anticipates victimization as the data used to construct the primary independent variables were collected in the first in-school survey while the data used to construct the variable victimization come from the in-home interviews conducted approximately a year after the first wave of in-school surveys were administered.  


```{r}
#Table 1: Descriptive Statistics

```


(6) Results: Answer the research question. 

